### ISSUE TITLE
GraphQL Storefront Style Guide

### ISSUE THREAD

**Issue by cassytaylor** [reactioncommerce/design#40]
Storefront Style Guide: http://zpl.io/VDz7kQJ

==================

Document the styles for:

- [x] Navigation styles
- [x] Responsive product grid (grid locks at 1440px across, breaks at...) 
- [x] Breakpoints / Notes on responsive behavior 
- [x] Typography
- [x] Colors 
- [x] Action buttons 
- [x] Form fields and form layout
- [x] Form elements - radio buttons, selectors
- [x] Product status badges (low inventory, sale, etc.)
- [x] Product grid controls (pagination, sort by/products per page dropdowns, filter menu)
- [x] Inline alerts, dot alerts
- [x] Accordions (like what we are using for address editor)
- [x] Productd module
- [x] Size and color selector
- [x] Icons

**Comment by rymorgan** [comment]
@cassytaylor let's strategize on this before we begin. For it to be useful I think it needs to -

- Be specific to ecommerce storefronts
- Provide a framework for other ecommerce storefronts style guides for reaction

In other words, I don't think we need to get super specific into form design because theoretically the component library it's built on would handle that. But, should say here are the alert colors that we used and how we used them. In other words here are the styles we overwrote because it made this storefront unique.
