### ISSUE TITLE
GraphQL Storefront - PDP Badging

### ISSUE THREAD

**Issue by cassytaylor** [reactioncommerce/design#44]
Design a badging system for the PDP.
- Low inventory
- Sold Out/Backordered
- Bestseller
- Sale

**Comment by cassytaylor** [comment]
**Sale:**
A Sale variant is depicted with the Sale badge (also used on the PDP) over the variant thumbnail image.  
![screen shot 2018-06-01 at 3 21 39 pm](https://user-images.githubusercontent.com/36006187/40864119-b06f0acc-65af-11e8-994f-b235202d47dc.png)

**Low inventory, out of stock, backordered messaging:**
These product statuses are conveyed through a message below the Variant option ("size" in the mocks), since these statuses generally happen at that level; 
![screen shot 2018-06-01 at 3 21 52 pm](https://user-images.githubusercontent.com/36006187/40864160-f00b96aa-65af-11e8-9896-27f66d161127.png)
![screen shot 2018-06-01 at 3 21 57 pm](https://user-images.githubusercontent.com/36006187/40864165-f5ffa236-65af-11e8-808b-05f86e061c17.png)
(the above mock depicts a variant that is completely sold out; sold out options are shown as disabled.) 
![screen shot 2018-06-01 at 3 22 09 pm](https://user-images.githubusercontent.com/36006187/40864185-130a317a-65b0-11e8-8b3f-4c7c8ba0697d.png)

Bestseller:
This badge is shown over the main product image on the PDP. 
![screen shot 2018-06-01 at 3 26 06 pm](https://user-images.githubusercontent.com/36006187/40864211-278faa44-65b0-11e8-9f81-57eefa0ba275.png)

**Comment by rymorgan** [comment]
I think you have to talk about how it works from a "badge category" or a rolled up perspective like we talked about this morning. So, be clear about groupings - 

- **Inventory badges** show up below option when variant and option have been selected. 
- **Sale/promotion badges** are the only badges that show up on the variant
- **Merchandising badges** show only on the large variant or option images 

Also, it just occurred to me that the variant isn't always going to be an image, so we need to see what would happen if it's a text variant or (and this is probably the least important since we haven't built this out yet) a swatch.
